#!/usr/bin/env bash

# Title:         greet
# Description:   a shell script to greet someone
# Author:        Amr Elsayyad <amrelsayyad96@outlook.com>
# Date:          2022-09-10
# Version:       0.0.1

# Exit codes
# ==========
# 0   no error
# 1   script interrupted
# 2   missing argument
# 3   invalid argument


# >>>>>>>>>>>>>>>>>>>>>>>> handler functions >>>>>>>>>>>>>>>>>>>>>>>>

# CTRL+C event handler
function on_ctrl_c() {
    echo # Set cursor to the next line of '^C'
    tput cnorm # show cursor. You need this if animation is used.
    # i.e. clean-up code here
    echo "terminated by signal interrupt" 1>&2
    exit 1 # Don't remove. Use a number (1-255) for error code.
}

# <<<<<<<<<<<<<<<<<<<<<<<< handler functions <<<<<<<<<<<<<<<<<<<<<<<<


# >>>>>>>>>>>>>>>>>>>>>>>> event handlers >>>>>>>>>>>>>>>>>>>>>>>>

# Register CTRL+C event handler
trap on_ctrl_c SIGINT

# <<<<<<<<<<<<<<<<<<<<<<<< event handlers <<<<<<<<<<<<<<<<<<<<<<<<


# >>>>>>>>>>>>>>>>>>>>>>>> functions >>>>>>>>>>>>>>>>>>>>>>>>

function show_help () {
    echo "
Usage: ${0} [OPTION]...
Displays a greeting message for a user.

OPTIONS:
    -h, --help      Show this help message.
    -m, --morning   Toggle morning instead of evening.
    -n, --name      User name. Default: current user
" # help message
}

# <<<<<<<<<<<<<<<<<<<<<<<< functions <<<<<<<<<<<<<<<<<<<<<<<<


# >>>>>>>>>>>>>>>>>>>>>>>> argument parsing >>>>>>>>>>>>>>>>>>>>>>>>

# default value for time of day
time='evening'

# argument parsing
POSITIONAL=()
while (( $# > 0 )); do
    case "${1}" in
        -h|--help)
        show_help
        exit 0
        ;;
        -m|--morning)
        # check if argument is after a positional argument
        if (( ${#POSITIONAL[@]} > 0 )); then
            echo "ERROR: argument '${POSITIONAL[@]}' not understood." 1>&2
            show_help
            exit 3
        fi
        # get switch arguments
        time='morning'
        shift # shift once since flags have no values
        ;;
        -n|--name)
        # check if argument is after a positional argument
        if (( ${#POSITIONAL[@]} > 0 )); then
            echo "ERROR: argument '${POSITIONAL[@]}' not understood." 1>&2
            show_help
            exit 3
        fi
        # get switch arguments
        numOfArgs=1 # number of switch arguments
        if (( $# < numOfArgs + 1 )); then
            echo "ERROR: missing argument for '${1}' option" >&2
            show_help
            exit 2
        else
            name=${2}
            shift $((numOfArgs + 1)) # shift 'numOfArgs + 1' to bypass switch and its value
        fi
        ;;
        *) # unknown flag/switch
        if [[ "${1}" =~ ^- ]]; then
            echo "ERROR: argument '${1}' is not understood."
            show_help
            exit 3
        else
            POSITIONAL+=("${1}")
            shift
        fi
        ;;
    esac
done

set -- "${POSITIONAL[@]}" # restore positional params

# <<<<<<<<<<<<<<<<<<<<<<<< argument parsing <<<<<<<<<<<<<<<<<<<<<<<<


# >>>>>>>>>>>>>>>>>>>>>>>> rest of code >>>>>>>>>>>>>>>>>>>>>>>>

# check for positional arguments
if (( ${#POSITIONAL[@]} > 0 )); then
    if [ "${name}" ]; then
        # if there are both a positional arg and a name arg
        echo "argument '${POSITIONAL[@]}' not understood." 1>&2
        show_help
        exit 3
    elif (( ${#POSITIONAL[@]} > 1 )); then
        # if more than 1 positional arg
        echo "argument '${POSITIONAL[@]:1}' not understood." 1>&2
        show_help
        exit 3
    else
        # if the positional arg is the name
        name=${POSITIONAL[0]}
    fi
fi

# check for existence of name
if [ "${name}" ]; then
    echo "Good ${time} ${name}!"
else
    echo "Good ${time} ${USER}!"
fi

# <<<<<<<<<<<<<<<<<<<<<<<< rest of code <<<<<<<<<<<<<<<<<<<<<<<<